name: Push Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bednar
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version tag
        id: get_version
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            bednar/app-store-connect-cli:latest
            bednar/app-store-connect-cli:${{ env.VERSION }}
          push: true
