name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mobile-app-cli:latest .

      - name: Run image
        run: docker run -it --rm mobile-app-cli:latest --help
